### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by mond77** [datenlord/rdma-sys#25]
```
[acb8du9j30@login03 ibv]$ cargo build
   Compiling rdma-sys v0.3.0
error: failed to run custom build command for `rdma-sys v0.3.0`

Caused by:
  process didn't exit successfully: `/work/home/acb8du9j30/rdma_test/ibv/target/debug/build/rdma-sys-9b0811c26487ede9/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBIBVERBS_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'please install libibverbs-dev 1.8.28)', /work/home/acb8du9j30/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/rdma-sys-0.3.0/build.rs:10:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
[acb8du9j30@login03 ibv]$ pkg-config --modversion libibverbs
1.10.30.0
```
Does it have to be version 1.8.28?

**Comment by pwang7** [comment]
newer version should be fine

**Comment by dhzzy88** [comment]
OS only suport debian ?


`# yum install libibverbs
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirrors.tuna.tsinghua.edu.cn
Package libibverbs-22.4-6.el7_9.x86_64 already installed and latest version
Nothing to do
# cargo build --release
   Compiling rdma-sys v0.3.0 (/root/rdma-sys)
error: failed to run custom build command for `rdma-sys v0.3.0 (/root/rdma-sys)`

Caused by:
  process didn't exit successfully: `/root/rdma-sys/target/release/build/rdma-sys-46b594d936f92173/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBIBVERBS_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'please install libibverbs-dev 1.8.28)', build.rs:10:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by GTwhy** [comment]
Hi, @dhzzy88 
Maybe you can install the lib on redhat by running
```
sudo yum install libibverbs-devel
```
The "libibverbs-dev" is the package name on debian, and it named "libibverbs-devel" on redhat.
I think the build script will find the lib with the lib name "libibvers".
We can add more tips in the code if you try it successfully.
